// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB10GIdra5Ehch7kY1UVVlHIyU2fyd06bU',
    appId: '1:316011780909:web:f187f10f27af3115d391a4',
    messagingSenderId: '316011780909',
    projectId: 'instgram-bdf9a',
    authDomain: 'instgram-bdf9a.firebaseapp.com',
    storageBucket: 'instgram-bdf9a.firebasestorage.app',
    measurementId: 'G-EWH71J3FT1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCm1NZYyFEpZd8HO0AWLrTaFaGPdsidoX8',
    appId: '1:316011780909:android:18f4d05a713c868fd391a4',
    messagingSenderId: '316011780909',
    projectId: 'instgram-bdf9a',
    storageBucket: 'instgram-bdf9a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWwxB0QGr-ZVOIBVTFEdQeen0RkWOVGJs',
    appId: '1:316011780909:ios:98dafdbaf5173ad9d391a4',
    messagingSenderId: '316011780909',
    projectId: 'instgram-bdf9a',
    storageBucket: 'instgram-bdf9a.firebasestorage.app',
    iosBundleId: 'com.example.form',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWwxB0QGr-ZVOIBVTFEdQeen0RkWOVGJs',
    appId: '1:316011780909:ios:98dafdbaf5173ad9d391a4',
    messagingSenderId: '316011780909',
    projectId: 'instgram-bdf9a',
    storageBucket: 'instgram-bdf9a.firebasestorage.app',
    iosBundleId: 'com.example.form',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB10GIdra5Ehch7kY1UVVlHIyU2fyd06bU',
    appId: '1:316011780909:web:f187f10f27af3115d391a4',
    messagingSenderId: '316011780909',
    projectId: 'instgram-bdf9a',
    authDomain: 'instgram-bdf9a.firebaseapp.com',
    storageBucket: 'instgram-bdf9a.firebasestorage.app',
    measurementId: 'G-EWH71J3FT1',
  );

}